using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Csorm2.Core.Cache.ChangeTracker;
using Csorm2.Core.Metadata;

namespace Csorm2.Core.Cache
{
    /// <summary>
    /// Central object Cache of the FrameWork
    /// the Cache saves all objects generated by CsOrm or supplied by the user for persisting
    /// the cache is organized by entity type and primary keys and for each object a CachEntry is made
    /// the cache also plays a major role in the ChangeTracking process, only objects that reside here can be tracked
    /// </summary>
    public class ObjectCache
    {
        private readonly DbContext _ctx;

        private Dictionary<Entity, Dictionary<object, CacheEntry>> _objectCache = new Dictionary<Entity, Dictionary<object, CacheEntry>>();
        
        /// <summary>
        /// Checks if a given entity with primary key exist in the cache
        /// </summary>
        /// <param name="entity"></param>
        /// <param name="primaryKey"></param>
        /// <returns></returns>
        public bool EntityExists(Entity entity, object primaryKey)
        {
            return _objectCache[entity].ContainsKey(primaryKey);
        }

        public ObjectCache(DbContext ctx)
        {
            _ctx = ctx;
            foreach (var (entityName, entity) in _ctx.Schema.EntityNameMap)
            {
                _objectCache[entity] = new Dictionary<object, CacheEntry>();
            }
        }
        /// <summary>
        /// Gets the CacheEntry for the given entity and primary key
        /// </summary>
        /// <param name="entity"></param>
        /// <param name="primaryKey"></param>
        /// <returns></returns>
        public CacheEntry GetEntry(Entity entity, object primaryKey) =>
            _objectCache[entity].GetValueOrDefault(primaryKey);
        
        /// <summary>
        /// Inserts a new CacheEntry
        /// throws an Exception if the Entry's primary key is null or if there already is an Entry with the key
        /// </summary>
        /// <param name="entry"></param>
        /// <returns></returns>
        /// <exception cref="Exception"></exception>
        
        internal CacheEntry InsertNew(CacheEntry entry)
        {
            var oldEntry = entry.PrimaryKey == null 
                ? null 
                : _objectCache[entry.Entity].GetValueOrDefault(entry.PrimaryKey);
            
            if(oldEntry != null) throw new Exception("Can only insert _new_ cache entries");
            _objectCache[entry.Entity][entry.PrimaryKey] = entry;
            return entry;
        }

        /// <summary>
        /// Collects all Changes for all tracked  objects
        /// </summary>
        /// <returns>List of all ValueChanges</returns>
        public IEnumerable<IValueChange> CollectChanges()
        {
            foreach (var (_, objects) in _objectCache)
            {
                foreach (var (pk, entity) in objects)
                {
                    foreach (var change in entity.ValueChanges())
                    {
                        yield return change;
                    }
                }
            }
        }
    }
}